blank_issues_enabled: false
contact_links:
  - name: ğŸ—¨ï¸ Molise Facebook group
    url: https://www.facebook.com/groups/molisefirmware
    about: Please ask and answer questions here.
  - name: ğŸ“– Marlin Documentation
    url: https://marlinfw.org/
    about: Lots of documentation on installing and using Marlin.
